using Microsoft.CodeAnalysis;

namespace WinRTWrapper.SourceGenerators
{
    public partial class WinRTWrapperGenerator
    {
        private const string GenerateMember =
            """
            // <auto-generated/>
            #pragma warning disable

            namespace WinRTWrapper.CodeAnalysis
            {
                /// <summary>
                /// Specifies the types of members to generate in the WinRT wrapper.
                /// </summary>
                internal enum GenerateMember
                {
                    /// <summary>
                    /// Specifies no members.
                    /// </summary>
                    None = 0,

                    /// <summary>
                    /// Specifies all members.
                    /// </summary>
                    All = (Interface << 1) | Defined | Interface,

                    /// <summary>
                    /// Specifies members that defined by wrapper class itself.
                    /// </summary>
                    Defined = 0x01,
            
                    /// <summary>
                    /// Specifies members that defined by target interfaces.
                    /// </summary>
                    Interface = Defined << 1,
                }
            }
            """;

        private const string GenerateWinRTWrapperAttribute =
            """
            // <auto-generated/>
            #pragma warning disable

            namespace WinRTWrapper.CodeAnalysis
            {
                /// <summary>
                /// Attribute to indicate that a class should be wrapped for WinRT compatibility.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
                internal sealed class GenerateWinRTWrapperAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// The type that this wrapper is targeting.
                    /// </summary>
                    private readonly global::System.Type target;

                    /// <summary>
                    /// The type of members to generate in the WinRT wrapper.
                    /// </summary>
                    private readonly global::WinRTWrapper.CodeAnalysis.GenerateMember member;

                    /// <summary>
                    /// The interfaces that this wrapper should implement.
                    /// </summary>
                    private readonly global::System.Type[] interfaces;

                    /// <summary>
                    /// Initializes a new instance of the <see cref="GenerateWinRTWrapperAttribute"/> class.
                    /// </summary>
                    /// <param name="target">The type that this wrapper is targeting.</param>
                    public GenerateWinRTWrapperAttribute(global::System.Type target)
            #if NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || WINDOWS_UWP
                        : this(target, global::WinRTWrapper.CodeAnalysis.GenerateMember.All, global::System.Array.Empty<global::System.Type>())
            #else
                        : this(target, global::WinRTWrapper.CodeAnalysis.GenerateMember.All, new global::System.Type[0])
            #endif
                    { }

                    /// <summary>
                    /// Initializes a new instance of the <see cref="GenerateWinRTWrapperAttribute"/> class.
                    /// </summary>
                    /// <param name="target">The type that this wrapper is targeting.</param>
                    /// <param name="member">The type of members to generate in the WinRT wrapper.</param>
                    public GenerateWinRTWrapperAttribute(global::System.Type target, global::WinRTWrapper.CodeAnalysis.GenerateMember member)
            #if NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || WINDOWS_UWP
                        : this(target, member, global::System.Array.Empty<global::System.Type>())
            #else
                        : this(target, member, new global::System.Type[0])
            #endif
                    { }

                    /// <summary>
                    /// Initializes a new instance of the <see cref="GenerateWinRTWrapperAttribute"/> class.
                    /// </summary>
                    /// <param name="target">The type that this wrapper is targeting.</param>
                    /// <param name="interfaces">The interfaces that this wrapper should implement.</param>
                    public GenerateWinRTWrapperAttribute(global::System.Type target, params global::System.Type[] interfaces)
                        : this(target, global::WinRTWrapper.CodeAnalysis.GenerateMember.Interface, interfaces)
                    { }

                    /// <summary>
                    /// Initializes a new instance of the <see cref="GenerateWinRTWrapperAttribute"/> class.
                    /// </summary>
                    /// <param name="target">The type that this wrapper is targeting.</param>
                    /// <param name="member">The type of members to generate in the WinRT wrapper.</param>
                    /// <param name="interfaces">The interfaces that this wrapper should implement.</param>
                    public GenerateWinRTWrapperAttribute(global::System.Type target, global::WinRTWrapper.CodeAnalysis.GenerateMember member, params global::System.Type[] interfaces)
                    {
                        this.target = target;
                        this.member = member;
                        this.interfaces = interfaces;
                    }

                    /// <summary>
                    /// Gets the type that this wrapper is targeting.
                    /// </summary>
                    public global::System.Type TargetType
                    {
                        get
                        {
                            return target;
                        }
                    }

                    /// <summary>
                    /// Gets the type of members to generate in the WinRT wrapper.
                    /// </summary>
                    public global::WinRTWrapper.CodeAnalysis.GenerateMember Member
                    {
                        get
                        {
                            return member;
                        }
                    }

                    /// <summary>
                    /// Gets the interfaces that this wrapper should implement.
                    /// </summary>
                    public global::System.Type[] Interfaces
                    {
                        get
                        {
                            return interfaces;
                        }
                    }
                }
            }
            """;

        private const string WinRTWrapperMarshallerAttribute =
            """
            // <auto-generated/>
            #pragma warning disable

            namespace WinRTWrapper.CodeAnalysis
            {
                /// <summary>
                /// Indicates an entry point type for defining a marshaller.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true)]
                internal sealed class WinRTWrapperMarshallerAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// The managed type to marshal.
                    /// </summary>
                    private readonly global::System.Type managedType;

                    /// <summary>
                    /// The type used for marshalling.
                    /// </summary>
                    private readonly global::System.Type wrapperType;

                    /// <summary>
                    /// Initializes a new instance of the <see cref="global::WinRTWrapper.CodeAnalysis.WinRTWrapperMarshallerAttribute"/> class.
                    /// </summary>
                    /// <param name="managedType">The managed type to marshal.</param>
                    /// <param name="wrapperType">The type used for marshalling.</param>
                    public WinRTWrapperMarshallerAttribute(global::System.Type managedType, global::System.Type wrapperType)
                    {
                        this.managedType = managedType;
                        this.wrapperType = wrapperType;
                    }

                    /// <summary>
                    /// Gets the managed type to marshal.
                    /// </summary>
                    public global::System.Type ManagedType
                    {
                        get
                        {
                            return managedType;
                        }
                    }

                    /// <summary>
                    /// Gets the type used for marshalling.
                    /// </summary>
                    public global::System.Type WrapperType
                    {
                        get
                        {
                            return wrapperType;
                        }
                    }
                }
            }
            """;

        private const string WinRTWrapperMarshallingAttribute =
            """
            // <auto-generated/>
            #pragma warning disable

            namespace WinRTWrapper.CodeAnalysis
            {
                /// <summary>
                /// Provides type information to a custom marshaller.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Delegate)]
                internal sealed class WinRTWrapperMarshallingAttribute : global::System.Attribute
                {
                    private readonly global::System.Type nativeType;

                    /// <summary>
                    /// Initializes a new instance of the <see cref="global::WinRTWrapper.CodeAnalysis.WinRTWrapperMarshallingAttribute" /> class.
                    /// </summary>
                    /// <param name="nativeType">The marshaller type used to convert the attributed type from managed to wrapper. This type must be attributed with <see cref="global::WinRTWrapper.CodeAnalysis.CustomMarshallerAttribute" />.</param>
                    public WinRTWrapperMarshallingAttribute(global::System.Type nativeType)
                    {
                        this.nativeType = nativeType;
                    }

                    /// <summary>
                    /// Gets the marshaller type used to convert the attributed type from managed to wrapper. This type must be attributed with <see cref="global::WinRTWrapper.CodeAnalysis.CustomMarshallerAttribute" />.
                    /// </summary>
                    public global::System.Type NativeType
                    {
                        get
                        {
                            return nativeType;
                        }
                    }
                }
            }
            """;

        private const string WinRTWrapperMarshalUsingAttribute =
            """
            // <auto-generated/>
            #pragma warning disable

            namespace WinRTWrapper.CodeAnalysis
            {
                /// <summary>
                /// Provides type information to a custom marshaller.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.ReturnValue | global::System.AttributeTargets.Property | global::System.AttributeTargets.Event)]
                internal sealed class WinRTWrapperMarshalUsingAttribute : global::System.Attribute
                {
                    private readonly global::System.Type nativeType;

                    /// <summary>
                    /// Initializes a new instance of the <see cref="global::WinRTWrapper.CodeAnalysis.WinRTWrapperMarshalUsingAttribute" /> class.
                    /// </summary>
                    /// <param name="nativeType">The marshaller type used to convert the attributed type from managed to wrapper. This type must be attributed with <see cref="global::WinRTWrapper.CodeAnalysis.CustomMarshallerAttribute" />.</param>
                    public WinRTWrapperMarshalUsingAttribute(global::System.Type nativeType)
                    {
                        this.nativeType = nativeType;
                    }

                    /// <summary>
                    /// Gets the marshaller type used to convert the attributed type from managed to wrapper. This type must be attributed with <see cref="global::WinRTWrapper.CodeAnalysis.CustomMarshallerAttribute" />.
                    /// </summary>
                    public global::System.Type NativeType
                    {
                        get
                        {
                            return nativeType;
                        }
                    }
                }
            }
            """;

        /// <summary>
        /// Emits the source for a given <see cref="GeneratedType"/> object.
        /// </summary>
        /// <param name="context">The input <see cref="IncrementalGeneratorPostInitializationContext"/> instance to use to emit code.</param>
        /// <param name="type">The <see cref="GeneratedType"/> object with info on the source to emit.</param>
        private void EmitPostGeneratedType(IncrementalGeneratorPostInitializationContext context)
        {
            context.AddSource($"{nameof(GenerateMember)}.g.cs", GenerateMember);
            context.AddSource($"{nameof(GenerateWinRTWrapperAttribute)}.g.cs", GenerateWinRTWrapperAttribute);
            context.AddSource($"{nameof(WinRTWrapperMarshallerAttribute)}.g.cs", WinRTWrapperMarshallerAttribute);
            context.AddSource($"{nameof(WinRTWrapperMarshallingAttribute)}.g.cs", WinRTWrapperMarshallingAttribute);
            context.AddSource($"{nameof(WinRTWrapperMarshalUsingAttribute)}.g.cs", WinRTWrapperMarshalUsingAttribute);
        }
    }

    /// <summary>
    /// Specifies the types of members to generate in the WinRT wrapper.
    /// </summary>
    internal enum GenerateMember
    {
        /// <summary>
        /// Specifies no members.
        /// </summary>
        None = 0,

        /// <summary>
        /// Specifies all members.
        /// </summary>
        All = (Interface << 1) | Defined | Interface,

        /// <summary>
        /// Specifies members that defined by wrapper class itself.
        /// </summary>
        Defined = 0x01,

        /// <summary>
        /// Specifies members that defined by target interfaces.
        /// </summary>
        Interface = Defined << 1,
    }
}
