<Project>

  <PropertyGroup>
    <Authors>wherewhere</Authors>
    <Copyright>Copyright © 2017 - 2025 wherewhere. All Rights Reserved.</Copyright>
    <LangVersion>latest</LangVersion>
    <PackageIconUrl>https://raw.githubusercontent.com/wherewhere/WinRTWrapper/main/logo.png</PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/wherewhere/WinRTWrapper</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/wherewhere/WinRTWrapper/releases</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageTags>COM;RPC;WinRT;Warpper</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/wherewhere/WinRTWrapper</RepositoryUrl>
    <VersionPrefix>0.0.1</VersionPrefix>
    <Description>A wrapper source generator for WinRT.</Description>
  </PropertyGroup>

</Project>
