// <auto-generated/>
#pragma warning disable

namespace WinRTWrapper.CodeAnalysis
{
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class,
        Inherited = false)]
    internal sealed class GenerateWinRTWrapperAttribute : global::System.Attribute
    {
        private readonly global::System.Type target;
        public global::System.Type TargetType
        {
            get
            {
                return target;
            }
        }

        public GenerateWinRTWrapperAttribute(global::System.Type target)
        {
            this.target = target;
        }
    }
}